raja = [1,2,4,5,6,3,4,5]
raja.sort()
print(raja)
raja.insert(2,10)
print(raja)
raja.append([11,24,45])
print(raja)
raja.extend([22,5,5,66])
print(raja)
print("pop:")
raja.pop(2)
print(raja)
print("index:")
c = raja.index(2)
print(c)
raja.reverse()
print(raja)
raja.remove(66)
print(raja)
c = raja.count(3)
print(c)
c = len(raja)
print(c)

